### PR TITLE
RIPPLE-77 Need to include DISCLAIMER and NOTICE files in package

### PR DESCRIPTION
**Pull request by TimBarham**

### CODE REVIEW

**Comment by TimBarham** [comment]
After this PR is merged, the 0.9.25 tag will need to be reapplied (with -f tag) and I'll build the package again.

**Comment by brentlintner** [comment]
Hey @TimBarham, I'm going to merge this ASAP! (sorry for the delay)

Regarding the tag change, while it is a small (non-code) change (i.e. package.json includes different files), would it make it more difficult for you if we bumped the version to 0.9.26 and pushed that as a tag (as well)?

The version is already in master, and, in the context of semantic versioning, changing what was in a version release should never happen. Plus, it would technically require the package.json 0.9.25 version change to be after this PR's commits.

**Comment by TimBarham** [comment]
Sure, bumping the version makes sense. Could you update package.json and the release notes when you tag?

**Comment by brentlintner** [comment]
Will do!

**Pull request merged**
