### PR TITLE
Fixed log message

### PR DESCRIPTION
**Pull request by ProH4Ck**
Earl Gray Tea doesn't exist but Earl Grey Tea is a very good drink!

### CODE REVIEW

**Comment by brentlintner** [comment]
@ProH4Ck LOL. Thanks so much for the PR. I can't *believe* that spelling wasn't correct, given the reference. I think that may have been me (a very long time ago). SHAME on me.

One thing, @ProH4Ck do you happen to have an ICLA filed for contributing to Apache Software Foundation projects?

If not, for expediency or if you don't want to, I can always commit this. :-)

**Comment by TimBarham** [comment]
Hey @brentlintner  - I don't believe we need an ICLA for a change as minimal (and is **important**!) as this one :smile: (since there isn't really any IP associated with this change).

**Comment by brentlintner** [comment]
@TimBarham ok, cool. I was not sure, even though I'd be one to want to do the same!

**Comment by brentlintner** [comment]
@TimBarham about to merge this, but I am having some new .ssh issues with Apache Git, so I should hopefully be able to merge once I figure that out, heh.

**Comment by brentlintner** [comment]
@TimBarham @ProH4Ck ok, figured it out. Merged. :-) Thanks a bunch for the contribution!

**Pull request merged**
